# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_company_premises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='registered_company_number',
            new_name='company_number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
    ]
