# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_company_care_of_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='po_box',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
