# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_company_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirmed_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='confirmed_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
