# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20170126_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_of_name', models.CharField(max_length=50, null=True)),
                ('premises', models.CharField(max_length=200, null=True)),
                ('address_line_1', models.CharField(max_length=200, null=True)),
                ('address_line_2', models.CharField(max_length=200, null=True)),
                ('po_box', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('locality', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='care_of_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='po_box',
        ),
        migrations.RemoveField(
            model_name='company',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='premises',
        ),
        migrations.RemoveField(
            model_name='company',
            name='region',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Address'),
        ),
    ]
